# Generated by Django 3.0.3 on 2021-06-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoHomeApp', '0002_room_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='sms',
            field=models.CharField(max_length=150, verbose_name='Сообщение чата'),
        ),
    ]
